"""Abstract transport protocol."""

from typing import Protocol, runtime_checkable


@runtime_checkable
class Transport(Protocol):
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def send_batch(self, events: list[dict]) -> bool: ...
    def is_healthy(self) -> bool: ...
